#シミュレーションを行う際の設定はこのファイルで設定します．


#終了条件についての設定です．
[EndChecker]
    
    #どのような方法で終了させるかを設定します．( "kGoalTape" / "kPosture" / "kPosition" )
    end_check_mode = "kGoalTape" 
    
    #終了条件がゴールテープに到達したか ( GoalTape ) の場合，ゴールテープのx座標を設定します．[mm]
    goal_tape_position_x = 1200.0
    
    #終了条件が目的の座標に到達したか ( Position ) の場合，目標の座標を設定します．[mm]
    target_position = "   500, 500, 0"
    
    #終了条件が目的の座標に到達したか ( Position ) の場合，目標の座標の許容誤差を設定します．[mm]
    target_position_allowable_error = 50.0
    
    #終了条件が目標姿勢となったか ( Posture ) の場合，目標の姿勢(xyzオイラー角)を設定します．[deg]
    target_posture = "     0.000,     0.000,     180.000"
    
    #終了条件が目標姿勢となったか ( Posture ) の場合，目標の姿勢の角度の許容誤差を設定します．[deg]
    target_posture_allowable_error_deg = 1.0

[Initial]
    
    #シミュレーション開始時のロボットの歩容を設定します．( "kNone" / "kLegUpDown" / "kLegHierarchyChange" / "kComMove" / "kComUpDown" / "kBodyPitchRot" / "kBodyYawRot" )
    initial_move = "kComMove"
    
    #シミュレーション開始時のロボットの位置を設定します．[mm]
    initial_positions = " 10, 0, 30"
    
#マップについての設定です．
[Map]
    
    #マップの作成方法を設定します．( "kForSimulation" / "kFromFile" )
    map_create_mode = "kForSimulation" 
    
    #マップの作成方法がファイルから読み込むモード ( FromFile ) の場合，マップのcsvファイルの名前を設定します．
    map_file_name = "MMCunevenness-170-10.csv"
    
    #マップの作成方法がシミュレーション専用マップを出力するモード ( ForSimulation ) の場合，マップのパラメータを記述したtomlファイルの名前を設定します．
    simulation_map_param_file_name = "simulation_map.toml"
    
#ロボットの操作方法の設定です．
[RobotOperator]
    
    #ロボットの操作方法が固定 ( Fixed ) の場合，その操作方法を指定するファイルを設定します．
    fixed_operate_file_name = "robot_operator.toml"
    
    #ロボットの操作方法を設定します．( "kForGloabalPathGenerate" / "kFixed" / "kForPath" )
    operate_mode = "kFixed" 
    
    #ロボットの操作方法がパス ( ForPath ) の場合，そのパスを設定します．
    path_points = [
    "  1200.000,     0.000,     0.000",
    "0, 0, 0",
    ]
    
