# TOMLという形式で記述しています．wikiでググるだけでもわかりやすい情報が出るので調べてみてください．
# メモ帳などのテキストエディタでもこのファイルは編集することができます．
# シミュレーション条件を変更したい場合は，ここから変更を行うようにしてみてください．
# このようにシャープで始まる行はコメントです．プログラムに影響を与えないため，メモ代わりに使うことができます．



title = "graph_search_settings"	#タイトルが"graph_search_settings"の物のみを読み込みます

major_version = 0			#バージョン表示です．ver major.minor.patch の順で記述されます．特に使う予定はないデータだけれど一応
minor_version = 5
patch_version = 0



#プログラムの起動モードの設定です
[mode]

ask_about_modes = true	# 起動時に実行モードについて質問をするようにします (true/false)

default_mode = "graph"	# defaultの実行モードを設定します．



#表示に関する設定です．グラフ探索をする際の設定で，viewerモードで実行した場合は無視されます．
[display]

cmd_output = true		# コマンドラインへの出力を行います (true/false)

gui_display = true		# GUI (dxlibによる表示)を行います (true/false)

window_size_x = 1280	# ウィンドウのサイズの横幅を設定します．xとyが16：9 になるように設定してください．

window_size_y = 720	# ウィンドウのサイズの縦幅を設定します．推奨値は (x, y) = (960, 540) (1280, 720) (1600, 900) (1920, 1080) などです．

window_fps = 60		# ウィンドウのフレームレートを設定します．推奨値は60か30です．



#マップ生成に関する設定です．グラフ探索をする際の設定で，viewerモードで実行した場合は無視されます．
[map]


